apiVersion: v1
kind: Service
metadata:
  name: manafood-microservico-usuario
spec:
  selector:
    app: manafood-microservico-usuario
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
