apiVersion: v1
kind: Secret
metadata:
  name: manafood-secrets
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "dummy"
  AWS_SECRET_ACCESS_KEY: "dummy"
  Jwt__SecretKey: "rF8wzYp2L#eX1v9sKd3@qMTuN6JBgCmySecretKey123456"