apiVersion: apps/v1
kind: Deployment
metadata:
  name: manafood-microservico-usuario
spec:
  replicas: 2
  selector:
    matchLabels:
      app: manafood-microservico-usuario
  template:
    metadata:
      labels:
        app: manafood-microservico-usuario
    spec:
      containers:
        - name: manafood-microservico-usuario
          image: manafood-microservico-usuario:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: manafood-config
            - secretRef:
                name: manafood-secrets
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
