apiVersion: apps/v1
kind: Deployment
metadata:
  name: manafood-dynamodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: manafood-dynamodb
  template:
    metadata:
      labels:
        app: manafood-dynamodb
    spec:
      containers:
        - name: dynamodb-local
          image: amazon/dynamodb-local:latest
          ports:
            - containerPort: 8000
          command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"