name: "Etapa: Pull Request"

on:
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]

jobs:
  # 1. Build e Testes
  build-and-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Rodar Testes
        run: dotnet test --configuration Release --no-build --verbosity normal
  
  # 2. Análise SonarQube
  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: build-and-tests
    steps:
      - name: Fazer checkout do repositório
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configurar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Instalar ferramentas
        run: |
          dotnet tool install --global dotnet-sonarscanner

      - name: Executar Análise SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin \
            /k:"mana-food_mana-food-microsservico-usuario" \
            /o:"mana-food" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.token="$SONAR_TOKEN" \
            /d:sonar.cs.vscoveragexml.reportsPaths="**/coverage.cobertura.xml" \
            /d:sonar.coverage.exclusions="**/Program.cs,**/Migrations/**,**/Tests/**" \
            /d:sonar.exclusions="**/bin/**,**/obj/**,**/*.dll,**/*.exe,**/Migrations/**,**/Tests/**"
          dotnet build --configuration Release --no-incremental
          dotnet test --configuration Release --no-build --verbosity normal \
            --collect:"XPlat Code Coverage" \
            --results-directory ./TestResults/
          echo "=== Coverage files generated ==="
          find ./TestResults -name "coverage.cobertura.xml" -type f -exec ls -lh {} \;
          dotnet sonarscanner end /d:sonar.token="$SONAR_TOKEN"